/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package padronelectoral;

import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import java.util.function.Predicate;
import java.util.stream.Collectors;
import javax.swing.JOptionPane;

/**
 *
 * @author Heiner
 */
public class GUI extends javax.swing.JFrame {
    ArrayList<Padron> Padron;//Lista que se genera de los datos del archivo
    Archivo objArchivo  = new Archivo();//Clase donde se guardan los datos del padron
    int contador = 0;
    private DefaultTableModel modelo;//Modelo para poder presentar en la tabla los datos separados
    List<Padron> padron;//Lista que se genera del filtro en la busqueda
    String textoBuscar,nombre,apellido1,apellido2;//textoBuscar que se obtiene de eliminar los espcios innecesario
    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        Padron = objArchivo.leer();//Aqui se pasan los datos al List
        setLocationRelativeTo(null);//Posicion del programa en la pantalla
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTMostrar = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        btnBuscar = new javax.swing.JButton();
        txtBuscar = new javax.swing.JTextField();
        btnSalir = new javax.swing.JButton();
        btnCargar = new javax.swing.JButton();
        checkCedula = new javax.swing.JCheckBox();
        checkNombre = new javax.swing.JCheckBox();
        checkApellido = new javax.swing.JCheckBox();
        checkCaducidad = new javax.swing.JCheckBox();
        checkCompleto = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        txtRegistro = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtEncontrado = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTMostrar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Cedula", "Genero", "Caducidad", "Nombre", "Primer Apellido", "Segundo Apellido", "Provincia"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTMostrar);

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnCargar.setText("Cargar");
        btnCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarActionPerformed(evt);
            }
        });

        checkCedula.setText("Cedula");

        checkNombre.setText("Nombre");

        checkApellido.setText("Apellido");

        checkCaducidad.setText("Caducidad Cedula");

        checkCompleto.setText("Nombre Completo");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(checkCedula)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(checkNombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(checkApellido)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(checkCaducidad))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCargar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSalir)
                    .addComponent(checkCompleto))
                .addContainerGap(115, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscar)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalir)
                    .addComponent(btnCargar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkCedula)
                    .addComponent(checkNombre)
                    .addComponent(checkApellido)
                    .addComponent(checkCaducidad)
                    .addComponent(checkCompleto))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jLabel2.setText("Cantidad de Registro:");

        jLabel1.setText("Cantidad de nombre completo igual:");

        jLabel3.setText("Encontrado:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEncontrado, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtEncontrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarActionPerformed
        // TODO add your handling code here:
        CargaInterFaz();
        cargarDatos(Padron);
        contador=0;//Contador se vuelve cero para comenzar el recorrido de la lista al principio
        txtRegistro.setText(String.valueOf(Padron.size()));
    }//GEN-LAST:event_btnCargarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        try{
            if(checkNombre.isSelected()){
                
                padron = filterPersonas(Padron, filtroNombre(txtBuscar.getText().trim().toUpperCase()));
                
            }
            else if(checkCedula.isSelected()){
                padron = filterPersonas(Padron, filtroCedula(txtBuscar.getText().trim()));
            }
            else if(checkApellido.isSelected()){
                padron = filterPersonas(Padron, filtroApellido1(txtBuscar.getText().toUpperCase().trim()));
            }
            else if(checkCaducidad.isSelected()){
                padron = filterPersonas(Padron, filtroCaducidad(txtBuscar.getText().trim()));
            }
            else if(checkCompleto.isSelected()){
                              
               //Se pasa la frase a una variable para hecer el cambio de espacios
               textoBuscar = txtBuscar.getText().trim();
               //Se reemplaza los espacios que tenga más de 2 a un solo espacio por palabra
               textoBuscar = textoBuscar.replaceAll(" {2,}", " ");
                //Aqui se separa el texto
                String[] informacion = textoBuscar.split(" ");
                nombre = informacion[0];
                apellido1 = informacion[1];
                apellido2 = informacion[2];
                padron = filterPersonas(Padron, (filtroNombre(nombre.trim().toUpperCase()).
                         and(filtroApellido1(apellido1.toUpperCase())).and(filtroApellido2(apellido2.toUpperCase()))));
               //Cantidad de nombre completos que se encontraron
                txtCantidad.setText(String.valueOf(padron.size()));
            }
                txtBuscar.setText(" ");
                //La cantidad de resultado en los filtros utilizado
                txtEncontrado.setText(String.valueOf(padron.size()));
                CargaInterFaz();
                cargarDatos(padron);
                contador=0;//Contador se vuelve cero para comenzar el recorrido de la lista al principio
        }catch (Exception e) {
            JOptionPane.showMessageDialog(null, "El dato no se encuentra en la Base");
        }
        
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }
    
    //Los predicados para los filtros de las busquedas
    public static Predicate <Padron> filtroCaducidad(String texto) {
        
            return p -> p.getCaducidad().equals(texto);     
    }
    
    public static Predicate <Padron> filtroApellido1(String texto) {
        
            return p -> p.getPrimerApe().startsWith(texto);     
    }
    
    public static Predicate <Padron> filtroApellido2(String texto) {
        
            return p -> p.getSegundoApe().startsWith(texto);     
    }
    
    public static Predicate <Padron> filtroCedula(String texto) {
        
            return p -> p.getCedula().equals(texto);     
    }
    
    public static Predicate <Padron> filtroNombre(String texto) {
        
            return p -> p.getNombre().startsWith(texto);     
    }
    
    //Filtro para la busqueda por cedula,nombre,apellido, caducidad y nombre completo
    public static List<Padron> filterPersonas(List<Padron> pacientes,
                                                Predicate<Padron> predicate)
    {
        return pacientes.stream()
                    .filter(predicate)
                    .collect(Collectors.<Padron>toList());
    }
    
    public void cargarDatos(List<Padron> padron)
    {   
             //Son las repeticiones que tiene que hacer para cargar los datos
             if(contador < padron.size()){
                 Padron p = padron.get(contador);
             
                 modelo.insertRow(contador,new Object[]{});
                 modelo.setValueAt(p.getCedula(),contador,0);
                 
                 if("1".equals(p.getGenero())){
                     modelo.setValueAt("Hombre",contador,1);
                 }else{
                     modelo.setValueAt("Mujer",contador,1);
                 }
                 
                 modelo.setValueAt(p.getCaducidad(),contador,2);
                 modelo.setValueAt(p.getNombre(),contador,3);
                 modelo.setValueAt(p.getPrimerApe(),contador,4);
                 modelo.setValueAt(p.getSegundoApe(), contador, 5);
                 
                 if(p.getProvincia().startsWith("6")){
                    modelo.setValueAt("Puntarenas", contador, 6);
                 }
                 contador++;
                 cargarDatos(padron);
             }
    }// registro de datos del Padron en la tabla
    
    //Procedimiento para cargar los campos en el jtable de nuestro registro de Padron
        public void CargaInterFaz(){
            String datos [][]={};
            String columna [] = {"Cedula","Genero","Caducidad","Nombre","Primer Apellido","Segundo Apellido","Provincia"};
            modelo = new DefaultTableModel(datos, columna);
            jTMostrar.setModel(modelo);
            
        }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCargar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JCheckBox checkApellido;
    private javax.swing.JCheckBox checkCaducidad;
    private javax.swing.JCheckBox checkCedula;
    private javax.swing.JCheckBox checkCompleto;
    private javax.swing.JCheckBox checkNombre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTMostrar;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtEncontrado;
    private javax.swing.JTextField txtRegistro;
    // End of variables declaration//GEN-END:variables
}
